variable "vpc_id" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "iam_instance_profile" {}
variable "policy_name" {}
variable "role_name" {}
variable "bucket_name" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_subnet_name" {}
variable "private_subnet_name" {}
variable "availability_zone" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "region" {}